// <auto-generated />
using System;
using IsTakip.Business;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IsTakip.Business.Migrations
{
    [DbContext(typeof(IsTakipContext))]
    [Migration("20260209152838_SeedDataEklendi")]
    partial class SeedDataEklendi
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("IsTakip.Entities.CalismaSuresi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Baslangic")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Bitis")
                        .HasColumnType("datetime2");

                    b.Property<int>("GorevId")
                        .HasColumnType("int");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("PersonelId")
                        .HasColumnType("int");

                    b.Property<bool>("SilindiMi")
                        .HasColumnType("bit");

                    b.Property<double>("ToplamSaat")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("GorevId");

                    b.HasIndex("PersonelId");

                    b.ToTable("CalismaSureleri");
                });

            modelBuilder.Entity("IsTakip.Entities.Departman", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<bool>("SilindiMi")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Departmanlar");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ad = "Yazılım Ekibi",
                            OlusturmaTarihi = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SilindiMi = false
                        },
                        new
                        {
                            Id = 2,
                            Ad = "Yönetim",
                            OlusturmaTarihi = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SilindiMi = false
                        });
                });

            modelBuilder.Entity("IsTakip.Entities.Dosya", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DosyaAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DosyaYolu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GorevId")
                        .HasColumnType("int");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<bool>("SilindiMi")
                        .HasColumnType("bit");

                    b.Property<string>("Uzanti")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("YuklemeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("YukleyenPersonelId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GorevId");

                    b.ToTable("Dosyalar");
                });

            modelBuilder.Entity("IsTakip.Entities.Gorev", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AtananPersonelId")
                        .HasColumnType("int");

                    b.Property<string>("Baslik")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("DurumId")
                        .HasColumnType("int");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int?>("OncelikId")
                        .HasColumnType("int");

                    b.Property<int>("ProjeId")
                        .HasColumnType("int");

                    b.Property<bool>("SilindiMi")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("TahminiBitis")
                        .HasColumnType("datetime2");

                    b.Property<int?>("TipId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AtananPersonelId");

                    b.HasIndex("DurumId");

                    b.HasIndex("OncelikId");

                    b.HasIndex("ProjeId");

                    b.HasIndex("TipId");

                    b.ToTable("Gorevler");
                });

            modelBuilder.Entity("IsTakip.Entities.GorevDurum", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<bool>("SilindiMi")
                        .HasColumnType("bit");

                    b.Property<int>("SiraNo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("GorevDurumlari");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ad = "Bekliyor",
                            OlusturmaTarihi = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SilindiMi = false,
                            SiraNo = 1
                        },
                        new
                        {
                            Id = 2,
                            Ad = "Analiz Aşamasında",
                            OlusturmaTarihi = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SilindiMi = false,
                            SiraNo = 2
                        },
                        new
                        {
                            Id = 3,
                            Ad = "Geliştiriliyor",
                            OlusturmaTarihi = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SilindiMi = false,
                            SiraNo = 3
                        },
                        new
                        {
                            Id = 4,
                            Ad = "Test Aşamasında",
                            OlusturmaTarihi = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SilindiMi = false,
                            SiraNo = 4
                        },
                        new
                        {
                            Id = 5,
                            Ad = "Tamamlandı",
                            OlusturmaTarihi = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SilindiMi = false,
                            SiraNo = 5
                        },
                        new
                        {
                            Id = 6,
                            Ad = "İptal Edildi",
                            OlusturmaTarihi = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SilindiMi = false,
                            SiraNo = 6
                        });
                });

            modelBuilder.Entity("IsTakip.Entities.GorevOncelik", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Derece")
                        .HasColumnType("int");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("Renk")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("SilindiMi")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("GorevOncelikleri");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ad = "Düşük",
                            Derece = 1,
                            OlusturmaTarihi = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Renk = "Gri",
                            SilindiMi = false
                        },
                        new
                        {
                            Id = 2,
                            Ad = "Normal",
                            Derece = 2,
                            OlusturmaTarihi = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Renk = "Mavi",
                            SilindiMi = false
                        },
                        new
                        {
                            Id = 3,
                            Ad = "Yüksek",
                            Derece = 3,
                            OlusturmaTarihi = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Renk = "Turuncu",
                            SilindiMi = false
                        },
                        new
                        {
                            Id = 4,
                            Ad = "Kritik (Acil)",
                            Derece = 4,
                            OlusturmaTarihi = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Renk = "Kırmızı",
                            SilindiMi = false
                        });
                });

            modelBuilder.Entity("IsTakip.Entities.GorevTipi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<bool>("SilindiMi")
                        .HasColumnType("bit");

                    b.Property<string>("Simge")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("GorevTipleri");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ad = "Geliştirme (Feature)",
                            OlusturmaTarihi = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SilindiMi = false,
                            Simge = "🔨"
                        },
                        new
                        {
                            Id = 2,
                            Ad = "Hata Düzeltme (Bug)",
                            OlusturmaTarihi = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SilindiMi = false,
                            Simge = "🐛"
                        },
                        new
                        {
                            Id = 3,
                            Ad = "Araştırma (R&D)",
                            OlusturmaTarihi = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SilindiMi = false,
                            Simge = "🔍"
                        },
                        new
                        {
                            Id = 4,
                            Ad = "Destek",
                            OlusturmaTarihi = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SilindiMi = false,
                            Simge = "🚑"
                        });
                });

            modelBuilder.Entity("IsTakip.Entities.GorevYorum", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("GorevId")
                        .HasColumnType("int");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("PersonelId")
                        .HasColumnType("int");

                    b.Property<bool>("SilindiMi")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("datetime2");

                    b.Property<string>("Yorum")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("GorevId");

                    b.HasIndex("PersonelId");

                    b.ToTable("GorevYorumlari");
                });

            modelBuilder.Entity("IsTakip.Entities.Musteri", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Adres")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<bool>("SilindiMi")
                        .HasColumnType("bit");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VergiNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Yetkili")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Musteriler");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ad = "Şirket İçi",
                            Adres = "Merkez",
                            Email = "info@sirket.com",
                            OlusturmaTarihi = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SilindiMi = false,
                            Telefon = "000",
                            VergiNo = "111",
                            Yetkili = "Ben"
                        });
                });

            modelBuilder.Entity("IsTakip.Entities.Personel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("DepartmanId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int?>("RolId")
                        .HasColumnType("int");

                    b.Property<string>("Sifre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("SilindiMi")
                        .HasColumnType("bit");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmanId");

                    b.HasIndex("RolId");

                    b.ToTable("Personeller");
                });

            modelBuilder.Entity("IsTakip.Entities.Proje", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("BaslangicTarihi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("BitisTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("Durum")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MusteriId")
                        .HasColumnType("int");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<bool>("SilindiMi")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("MusteriId");

                    b.ToTable("Projeler");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Aciklama = "Projesiz görevler buraya",
                            Ad = "Genel İşler",
                            BaslangicTarihi = new DateTime(2026, 2, 9, 18, 28, 37, 929, DateTimeKind.Local).AddTicks(3323),
                            Durum = "Aktif",
                            MusteriId = 1,
                            OlusturmaTarihi = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SilindiMi = false
                        });
                });

            modelBuilder.Entity("IsTakip.Entities.Rol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Kod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<bool>("SilindiMi")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Roller");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ad = "Yönetici",
                            Kod = "ADMIN",
                            OlusturmaTarihi = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SilindiMi = false
                        },
                        new
                        {
                            Id = 2,
                            Ad = "Takım Lideri",
                            Kod = "LEAD",
                            OlusturmaTarihi = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SilindiMi = false
                        },
                        new
                        {
                            Id = 3,
                            Ad = "Personel",
                            Kod = "USER",
                            OlusturmaTarihi = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SilindiMi = false
                        });
                });

            modelBuilder.Entity("IsTakip.Entities.CalismaSuresi", b =>
                {
                    b.HasOne("IsTakip.Entities.Gorev", "Gorev")
                        .WithMany("CalismaSureleri")
                        .HasForeignKey("GorevId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IsTakip.Entities.Personel", "Personel")
                        .WithMany()
                        .HasForeignKey("PersonelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gorev");

                    b.Navigation("Personel");
                });

            modelBuilder.Entity("IsTakip.Entities.Dosya", b =>
                {
                    b.HasOne("IsTakip.Entities.Gorev", "Gorev")
                        .WithMany("Dosyalar")
                        .HasForeignKey("GorevId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gorev");
                });

            modelBuilder.Entity("IsTakip.Entities.Gorev", b =>
                {
                    b.HasOne("IsTakip.Entities.Personel", "AtananPersonel")
                        .WithMany("Gorevler")
                        .HasForeignKey("AtananPersonelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IsTakip.Entities.GorevDurum", "Durum")
                        .WithMany("Gorevler")
                        .HasForeignKey("DurumId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IsTakip.Entities.GorevOncelik", "Oncelik")
                        .WithMany("Gorevler")
                        .HasForeignKey("OncelikId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("IsTakip.Entities.Proje", "Proje")
                        .WithMany("Gorevler")
                        .HasForeignKey("ProjeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IsTakip.Entities.GorevTipi", "Tip")
                        .WithMany("Gorevler")
                        .HasForeignKey("TipId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("AtananPersonel");

                    b.Navigation("Durum");

                    b.Navigation("Oncelik");

                    b.Navigation("Proje");

                    b.Navigation("Tip");
                });

            modelBuilder.Entity("IsTakip.Entities.GorevYorum", b =>
                {
                    b.HasOne("IsTakip.Entities.Gorev", "Gorev")
                        .WithMany("Yorumlar")
                        .HasForeignKey("GorevId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IsTakip.Entities.Personel", "Personel")
                        .WithMany()
                        .HasForeignKey("PersonelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Gorev");

                    b.Navigation("Personel");
                });

            modelBuilder.Entity("IsTakip.Entities.Personel", b =>
                {
                    b.HasOne("IsTakip.Entities.Departman", "Departman")
                        .WithMany("Personeller")
                        .HasForeignKey("DepartmanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IsTakip.Entities.Rol", "Rol")
                        .WithMany("Personeller")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Departman");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("IsTakip.Entities.Proje", b =>
                {
                    b.HasOne("IsTakip.Entities.Musteri", "Musteri")
                        .WithMany("Projeler")
                        .HasForeignKey("MusteriId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Musteri");
                });

            modelBuilder.Entity("IsTakip.Entities.Departman", b =>
                {
                    b.Navigation("Personeller");
                });

            modelBuilder.Entity("IsTakip.Entities.Gorev", b =>
                {
                    b.Navigation("CalismaSureleri");

                    b.Navigation("Dosyalar");

                    b.Navigation("Yorumlar");
                });

            modelBuilder.Entity("IsTakip.Entities.GorevDurum", b =>
                {
                    b.Navigation("Gorevler");
                });

            modelBuilder.Entity("IsTakip.Entities.GorevOncelik", b =>
                {
                    b.Navigation("Gorevler");
                });

            modelBuilder.Entity("IsTakip.Entities.GorevTipi", b =>
                {
                    b.Navigation("Gorevler");
                });

            modelBuilder.Entity("IsTakip.Entities.Musteri", b =>
                {
                    b.Navigation("Projeler");
                });

            modelBuilder.Entity("IsTakip.Entities.Personel", b =>
                {
                    b.Navigation("Gorevler");
                });

            modelBuilder.Entity("IsTakip.Entities.Proje", b =>
                {
                    b.Navigation("Gorevler");
                });

            modelBuilder.Entity("IsTakip.Entities.Rol", b =>
                {
                    b.Navigation("Personeller");
                });
#pragma warning restore 612, 618
        }
    }
}
